# Generated by Django 4.2.20 on 2026-08-25 11:16

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Product description with rich text formatting'),
        ),
    ]
