# Generated by Django 6.0.5 on 2026-08-29 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_on_sale_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale_price',
            field=models.IntegerField(blank=True, help_text='Sale price in Toman (optional). If set, discount % is calculated automatically', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Regular price of the product in Toman', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
