# Generated by Django 4.2.20 on 2026-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_pricing_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش در «محصولات منتخب» صفحه اصلی (کوچک\u200cتر = جلوتر)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='نمایش در بخش «محصولات منتخب» صفحه اصلی'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'featured_order'], name='products_pr_is_feat_b86213_idx'),
        ),
    ]
