# Generated by Django 4.2.20 on 2026-09-04 22:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_product_featured_order_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AlterModelOptions(
            name='productlike',
            options={'verbose_name': 'پسند محصول', 'verbose_name_plural': 'پسندهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='productsave',
            options={'verbose_name': 'محصول ذخیره\u200cشده', 'verbose_name_plural': 'محصولات ذخیره\u200cشده'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد این دسته\u200cبندی (به\u200cصورت خودکار ثبت می\u200cشود).', verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='کاربری که این دسته\u200cبندی را ایجاد کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='نام دسته\u200cبندی، مثلاً «گلدان» یا «ابزارآلات آشپزخانه». در فروشگاه و در فهرست دسته\u200cبندی\u200cها نمایش داده می\u200cشود.', max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='اگر این دسته\u200cبندی زیرمجموعه\u200cی دسته\u200cبندی دیگری است، آن را اینجا انتخاب کنید. برای دسته\u200cبندی\u200cهای اصلی (سطح اول)، این فیلد را خالی بگذارید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='بخشی از آدرس این دسته\u200cبندی در سایت. اگر خالی بگذارید، به\u200cطور خودکار از روی نام ساخته می\u200cشود.', max_length=255, unique=True, verbose_name='اسلاگ (شناسه URL)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین ویرایش این دسته\u200cبندی (به\u200cصورت خودکار ثبت می\u200cشود).', verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='call_for_price',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، به\u200cجای قیمت به مشتری عبارت «تماس بگیرید» نمایش داده می\u200cشود و فیلدهای قیمت و قیمت با تخفیف غیرفعال می\u200cشوند. برای محصولاتی که قیمت ثابتی ندارند مناسب است.', verbose_name='تماس برای قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='دسته\u200cبندی\u200cای که این محصول به آن تعلق دارد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(help_text='تصویر اصلی محصول که در فهرست محصولات و بالای صفحه اختصاصی آن نمایش داده می\u200cشود. تصویر روشن و باکیفیت انتخاب کنید.', upload_to='products/covers/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ثبت این محصول (به\u200cصورت خودکار ثبت می\u200cشود).', verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(help_text='کاربری که این محصول را در پنل مدیریت ثبت کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='توضیحات کامل محصول. می\u200cتوانید از قالب\u200cبندی متن (پررنگ، لیست، تصویر و غیره) استفاده کنید؛ این متن در صفحه اختصاصی محصول نمایش داده می\u200cشود.', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_in_special_sales',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، این محصول واجد شرایط نمایش در بخش «فروش ویژه» سایت می\u200cشود. برای نمایش واقعی در صفحه اصلی، باید در بخش «محصولات فروش ویژه» پنل صفحه اصلی نیز انتخاب شود.', verbose_name='فروش ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش در «محصولات منتخب» صفحه اصلی (کوچک\u200cتر = جلوتر)', verbose_name='ترتیب نمایش ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='نمایش در بخش «محصولات منتخب» صفحه اصلی', verbose_name='محصول ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='نام محصول همان\u200cطور که در فروشگاه نمایش داده می\u200cشود. باید یکتا باشد؛ دو محصول نمی\u200cتوانند نام یکسان داشته باشند.', max_length=255, unique=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_sale_price',
            field=models.IntegerField(blank=True, help_text='قیمت محصول در زمان تخفیف (اختیاری). اگر مقداری وارد کنید، درصد تخفیف به\u200cطور خودکار محاسبه و در سایت نمایش داده می\u200cشود. باید کمتر یا مساوی «قیمت» باشد.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت با تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='قیمت عادی محصول به تومان و بدون جداکننده هزارگان (مثلاً برای دویست هزار تومان عدد 200000 را وارد کنید). اگر «تماس برای قیمت» فعال باشد، این مقدار نادیده گرفته و صفر ذخیره می\u200cشود.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False, help_text='در صورت غیرفعال بودن، این محصول در فروشگاه نمایش داده نمی\u200cشود اما در پنل مدیریت باقی می\u200cماند؛ برای پیش\u200cنویس کردن محصولات ناتمام مناسب است.', verbose_name='منتشر شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='بخشی از آدرس این محصول در سایت. اگر خالی بگذارید، به\u200cطور خودکار از روی نام ساخته می\u200cشود.', max_length=255, unique=True, verbose_name='اسلاگ (شناسه URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='برچسب\u200cهای مرتبط با این محصول برای جست\u200cوجوی بهتر و نمایش محصولات مشابه.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین ویرایش این محصول (به\u200cصورت خودکار ثبت می\u200cشود).', verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان افزودن این تصویر (به\u200cصورت خودکار ثبت می\u200cشود).', verbose_name='تاریخ افزودن'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='یکی از تصاویر گالری این محصول (علاوه بر تصویر شاخص).', upload_to='products/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش این تصویر در گالری محصول (کوچک\u200cتر = جلوتر).', verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='محصولی که این تصویر به گالری آن تعلق دارد.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان پسندیدن این محصول توسط کاربر.', verbose_name='تاریخ پسندیدن'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(help_text='محصولی که پسندیده شده است.', on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_users', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='user',
            field=models.ForeignKey(help_text='کاربری که این محصول را پسندیده است.', on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productsave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ذخیره این محصول توسط کاربر.', verbose_name='تاریخ ذخیره'),
        ),
        migrations.AlterField(
            model_name='productsave',
            name='product',
            field=models.ForeignKey(help_text='محصولی که ذخیره شده است.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productsave',
            name='user',
            field=models.ForeignKey(help_text='کاربری که این محصول را ذخیره کرده است.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
