# Generated by Django 4.2.20 on 2026-09-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='بخشی از آدرس این دسته\u200cبندی در سایت. اگر خالی بگذارید، به\u200cطور خودکار از روی نام ساخته می\u200cشود.', max_length=255, unique=True, verbose_name='اسلاگ (شناسه URL)'),
        ),
    ]
