# Generated by Django 4.2.20 on 2026-09-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='در صورت نیاز، آدرس اصلی و ترجیحی این محصول را وارد کنید.', verbose_name='آدرس canonical'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='توضیح کوتاهی درباره محتوای محصول که می\u200cتواند در نتایج موتورهای جستجو نمایش داده شود.', verbose_name='توضیحات سئو'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='عنوانی که موتورهای جستجو برای این محصول نمایش می\u200cدهند. بهتر است کوتاه، دقیق و مرتبط با محتوای محصول باشد.', max_length=200, verbose_name='عنوان سئو'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک\u200cگذاری محصول در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', null=True, upload_to='products/og-images/%Y/%m/', verbose_name='تصویر اشتراک\u200cگذاری'),
        ),
    ]
