# Generated by Django 4.2.20 on 2026-09-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_canonical_url_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='در صورت نیاز به آدرس اختصاصی، این فیلد را پر کنید. در غیر این صورت خالی بگذارید تا آدرس خودکار سیستم اعمال شود.', max_length=500, verbose_name='آدرس canonical'),
        ),
    ]
