# Generated by Django 4.2.20 on 2026-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_canonical_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(help_text='تصویر اصلی محصول که در فهرست محصولات و بالای صفحه اختصاصی آن نمایش داده می\u200cشود. تصویر روشن و باکیفیت انتخاب کنید.', max_length=500, upload_to='products/covers/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک\u200cگذاری محصول در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', max_length=500, null=True, upload_to='products/og-images/%Y/%m/', verbose_name='تصویر اشتراک\u200cگذاری'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='یکی از تصاویر گالری این محصول (علاوه بر تصویر شاخص).', max_length=500, upload_to='products/images/', verbose_name='تصویر'),
        ),
    ]
