# Generated by Django 4.2.20 on 2026-09-23 12:29

from django.db import migrations, models


def update_existing_featured_order(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(featured_order=0).update(featured_order=2)


def reverse_featured_order(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_cover_image_alter_product_og_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['featured_order', '-created_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_order',
            field=models.PositiveIntegerField(default=2, help_text='ترتیب نمایش در فروشگاه و بخش محصولات منتخب (کوچک\u200cتر = جلوتر)', verbose_name='ترتیب نمایش ویژه'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured_order', '-created_at'], name='products_pr_feature_f9d327_idx'),
        ),
        migrations.RunPython(
            update_existing_featured_order,
            reverse_code=reverse_featured_order,
        ),
    ]

