# Generated by Django 4.2.20 on 2026-10-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_options_alter_product_featured_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='کلمه یا عبارت کلیدی اصلی که این محصول برای آن در موتورهای جستجو بهینه\u200cسازی می\u200cشود.', max_length=150, verbose_name='کلمه کلیدی کانونی'),
        ),
    ]
