# Generated by Django 4.2.20 on 2026-09-17 17:25

import apps.sms_service.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='نام و نام خانوادگی برای شناسایی در دفترچه تلفن', max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(help_text='شماره موبایل معتبر ایران (مانند 09123456789)', max_length=15, unique=True, validators=[apps.sms_service.utils.validate_iranian_mobile], verbose_name='شماره موبایل')),
                ('notes', models.TextField(blank=True, help_text='توضیحات اختیاری درباره این مخاطب', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'مخاطب دفترچه تلفن',
                'verbose_name_plural': 'دفترچه تلفن',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField(verbose_name='متن خام پیامک')),
                ('recipient_source', models.CharField(choices=[('users', 'کاربران سایت'), ('contacts', 'دفترچه تلفن'), ('mixed', 'ترکیبی (کاربران و دفترچه تلفن)')], default='mixed', max_length=20, verbose_name='منبع مخاطبین')),
                ('total_selected', models.PositiveIntegerField(default=0, verbose_name='تعداد کل انتخاب شده')),
                ('total_deduplicated', models.PositiveIntegerField(default=0, verbose_name='تعداد پس از حذف تکراری')),
                ('successful_count', models.PositiveIntegerField(default=0, verbose_name='ارسال\u200cهای موفق')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='ارسال\u200cهای ناموفق')),
                ('status', models.CharField(choices=[('pending', 'در حال پردازش'), ('completed', 'موفق'), ('partial_failure', 'ارسال جزئی (همراه با خطا)'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
            ],
            options={
                'verbose_name': 'کمپین ارسال پیامک',
                'verbose_name_plural': 'تاریخچه ارسال\u200cهای پیامک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsRecipientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('user', 'کاربر سایت'), ('contact', 'مخاطب دفترچه')], max_length=20, verbose_name='نوع مخاطب')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('final_message', models.TextField(verbose_name='متن نهایی ارسال\u200cشده')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('skipped_duplicate', 'حذف به دلیل شماره تکراری'), ('skipped_invalid', 'شماره نامعتبر')], max_length=20, verbose_name='وضعیت ارسال')),
                ('provider_rec_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه رسید درگاه (recId)')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='کد خطای درگاه')),
                ('error_message', models.TextField(blank=True, verbose_name='شرح خطای درگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='sms_service.smscampaign', verbose_name='کمپین پیامکی')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='sms_service.contact', verbose_name='مخاطب دفترچه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سایت')),
            ],
            options={
                'verbose_name': 'گزارش پیامک گیرنده',
                'verbose_name_plural': 'گزارش پیامک\u200cهای ارسالی',
                'ordering': ['-created_at'],
            },
        ),
    ]
