# Generated by Django 4.2.20 on 2026-09-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='has_price_access',
            field=models.BooleanField(default=True, help_text='اگر غیرفعال شود، این کاربر باوجود ورود به حساب کاربری، به\u200cجای قیمت واقعی محصولات فقط پیام «قیمت ویژه\u200cی حساب\u200cهای تأییدشده» را می\u200cبیند.', verbose_name='دسترسی به مشاهده قیمت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='شماره موبایل کاربر، مثلاً 09123456789. اگر پر شود، باید برای هر کاربر منحصربه\u200cفرد باشد.', max_length=15, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
