# Generated by Django 4.2.20 on 2026-09-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(help_text='تصویر تمام\u200cصفحه پشت متن اسلاید. بهتر است افقی و با کیفیت باشد.', upload_to='home/hero/', verbose_name='تصویر پس\u200cزمینه')),
                ('eyebrow', models.CharField(blank=True, help_text='متن کوچک بالای عنوان (مثلاً «مجموعه\u200cی پاییز ۱۴۰۳»).', max_length=120, verbose_name='پیش\u200cعنوان')),
                ('title', models.TextField(help_text='عنوان بزرگ اسلاید. برای شکستن خط، Enter بزنید.', verbose_name='عنوان اصلی')),
                ('subtitle', models.TextField(blank=True, help_text='یک یا دو جمله زیر عنوان.', verbose_name='توضیح کوتاه')),
                ('cta_label', models.CharField(blank=True, help_text='متن روی دکمه\u200cی طلایی. خالی بگذارید تا دکمه نمایش داده نشود.', max_length=60, verbose_name='متن دکمه')),
                ('cta_url_name', models.CharField(blank=True, choices=[('home:home', 'خانه'), ('products:product_list', 'فروشگاه (همه محصولات)'), ('products:special_sales', 'فروش ویژه'), ('products:category_list', 'دسته\u200cبندی\u200cها'), ('blogs:article_list', 'مجله سیدوس'), ('support:ticket_list', 'پشتیبانی (لیست تیکت\u200cها)'), ('support:ticket_create', 'ثبت تیکت جدید'), ('accounts:login', 'ورود'), ('accounts:logout', 'خروج'), ('accounts:profile', 'پروفایل کاربر')], help_text='صفحه\u200cای که با کلیک روی دکمه باز می\u200cشود.', max_length=64, verbose_name='مقصد دکمه')),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال کنید تا اسلاید از روی سایت مخفی شود.', verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='کوچک\u200cتر = جلوتر.', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'اسلاید هیرو',
                'verbose_name_plural': 'اسلایدهای هیرو',
                'ordering': ['order', 'id'],
            },
        ),
    ]
