# Generated by Django 4.2.20 on 2026-09-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_featured_order_product_is_featured_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, help_text='متن کوتاهی که زیر نام محصول در بخش پرفروش\u200cها نمایش داده می\u200cشود.', max_length=200, verbose_name='زیرعنوان')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر = نمایش جلوتر در بخش پرفروش\u200cها.', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='اگر غیرفعال باشد، محصول در بخش پرفروش\u200cها نمایش داده نمی\u200cشود.', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('product', models.OneToOneField(help_text='محصولی که به\u200cعنوان پرفروش در صفحه اصلی نمایش داده می\u200cشود.', on_delete=django.db.models.deletion.CASCADE, related_name='home_bestseller', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول پرفروش',
                'verbose_name_plural': 'محصولات پرفروش',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='home_bestse_is_acti_e13b67_idx')],
            },
        ),
    ]
