# Generated by Django 4.2.20 on 2026-09-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_featured_order_product_is_featured_and_more'),
        ('home', '0002_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSaleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر = نمایش جلوتر در بخش فروش ویژه.', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='اگر غیرفعال باشد، محصول در بخش فروش ویژه نمایش داده نمی\u200cشود.', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('product', models.OneToOneField(help_text='فقط محصولاتی که «فروش ویژه» آن\u200cها فعال است قابل انتخاب هستند.', limit_choices_to={'featured_in_special_sales': True}, on_delete=django.db.models.deletion.CASCADE, related_name='home_special_sale', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول فروش ویژه',
                'verbose_name_plural': 'محصولات فروش ویژه',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='home_specia_is_acti_cd5a9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='تصویری که مخصوص نمایش این دسته\u200cبندی در صفحه اصلی است (مستقل از خود دسته\u200cبندی).', upload_to='home/featured_categories/', verbose_name='تصویر')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر = نمایش جلوتر در بخش دسته\u200cبندی\u200cهای منتخب.', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='اگر غیرفعال باشد، این دسته\u200cبندی در صفحه اصلی نمایش داده نمی\u200cشود.', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.OneToOneField(help_text='دسته\u200cبندی\u200cای که در بخش «دسته\u200cبندی\u200cهای منتخب» صفحه اصلی نمایش داده می\u200cشود.', on_delete=django.db.models.deletion.CASCADE, related_name='home_featured', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی منتخب',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای منتخب',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='home_featur_is_acti_444adf_idx')],
            },
        ),
    ]
