# Generated by Django 4.2.20 on 2026-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_specialsalefeature_featuredcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='آدرسی که کاربر برای عضویت در خبرنامه سیدوس وارد کرده است. هر ایمیل فقط یک\u200cبار می\u200cتواند ثبت شود.', max_length=254, unique=True, verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان عضویت در خبرنامه (به\u200cصورت خودکار ثبت می\u200cشود).', verbose_name='تاریخ ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'مشترک خبرنامه',
                'verbose_name_plural': 'مشترکین خبرنامه',
                'ordering': ['-created_at'],
            },
        ),
    ]
