# Generated by Django 4.2.20 on 2026-09-09 18:07

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='نام یا عنوان فایل لیست قیمت (مثلاً: لیست قیمت عمده پاییز ۱۴۰۳).', max_length=200, verbose_name='عنوان لیست قیمت')),
                ('file', models.FileField(help_text='فایل با فرمت\u200cهای مجاز PDF، JPG، JPEG، یا PNG.', upload_to=apps.home.models.price_list_upload_path, validators=[apps.home.models.validate_price_list_file], verbose_name='فایل لیست قیمت')),
                ('description', models.TextField(blank=True, help_text='توضیحات اختیاری درباره این لیست قیمت.', verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، این لیست قیمت برای کاربران نمایش داده نمی\u200cشود.', verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='کوچک\u200cتر = نمایش جلوتر.', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'لیست قیمت',
                'verbose_name_plural': 'لیست\u200cهای قیمت',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
