# Generated by Django 6.0.5 on 2026-10-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactmessage'),
        ('products', '0013_alter_product_options_alter_product_featured_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsalefeature',
            name='product',
            field=models.OneToOneField(help_text='محصولی که در بخش فروش ویژه صفحه اصلی نمایش داده می\u200cشود.', on_delete=django.db.models.deletion.CASCADE, related_name='home_special_sale', to='products.product', verbose_name='محصول'),
        ),
    ]
