# Generated by Django 4.2.20 on 2026-08-24 15:34

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان اصلی مقاله را وارد کنید.', max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.CharField(help_text='شناسه یکتای مقاله در URL. می\u200cتواند شامل حروف فارسی، اعداد و خط تیره باشد.', max_length=255, unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(help_text='خلاصه کوتاهی از مقاله که در کارت\u200cها و لیست مقالات نمایش داده می\u200cشود.', verbose_name='خلاصه مقاله')),
                ('featured_image', models.ImageField(blank=True, help_text='تصویر اصلی مقاله که در لیست مقالات و صفحه جزئیات نمایش داده می\u200cشود.', null=True, upload_to='blogs/articles/%Y/%m/', verbose_name='تصویر شاخص')),
                ('content', models.TextField(help_text='محتوای کامل مقاله با فرمت HTML که توسط CKEditor 5 تولید می\u200cشود.', verbose_name='متن مقاله')),
                ('reading_time', models.PositiveIntegerField(help_text='زمان تقریبی مطالعه مقاله بر حسب دقیقه (فقط عدد وارد شود).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='زمان مطالعه')),
                ('published_at', models.DateTimeField(blank=True, help_text='تاریخ و زمان انتشار مقاله. برای پیش\u200cنویس می\u200cتواند خالی باشد.', null=True, verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=False, help_text='با فعال کردن این گزینه، مقاله در سایت برای کاربران قابل مشاهده خواهد بود.', verbose_name='انتشار مقاله')),
                ('meta_title', models.CharField(blank=True, help_text='عنوانی که موتورهای جستجو برای این مقاله نمایش می\u200cدهند. بهتر است کوتاه، دقیق و مرتبط با محتوای مقاله باشد.', max_length=200, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, help_text='توضیح کوتاهی درباره محتوای مقاله که می\u200cتواند در نتایج موتورهای جستجو نمایش داده شود.', verbose_name='توضیحات سئو')),
                ('canonical_url', models.URLField(blank=True, help_text='در صورت نیاز، آدرس اصلی و ترجیحی این مقاله را وارد کنید.', verbose_name='آدرس canonical')),
                ('og_title', models.CharField(blank=True, help_text='عنوانی که هنگام اشتراک\u200cگذاری مقاله در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', max_length=200, verbose_name='عنوان اشتراک\u200cگذاری')),
                ('og_description', models.TextField(blank=True, help_text='توضیحی که هنگام اشتراک\u200cگذاری مقاله در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', verbose_name='توضیحات اشتراک\u200cگذاری')),
                ('og_image', models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک\u200cگذاری مقاله در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', null=True, upload_to='blogs/og-images/%Y/%m/', verbose_name='تصویر اشتراک\u200cگذاری')),
                ('robots', models.CharField(blank=True, default='index,follow', help_text='تنظیمات مربوط به نحوه مشاهده و ایندکس شدن مقاله توسط موتورهای جستجو.', max_length=50, verbose_name='تنظیمات robots')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد مقاله (به صورت خودکار ثبت می\u200cشود).', verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی مقاله (به صورت خودکار ثبت می\u200cشود).', verbose_name='تاریخ به\u200cروزرسانی')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='برچسب\u200cهای مرتبط با مقاله را وارد کنید. این برچسب\u200cها برای نمایش مقالات مرتبط استفاده می\u200cشوند.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='blogs_artic_is_publ_465d76_idx')],
            },
        ),
    ]
