# Generated by Django 4.2.20 on 2026-08-24 16:40

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='محتوای کامل مقاله با فرمت HTML که توسط CKEditor 5 تولید می\u200cشود.', verbose_name='متن مقاله'),
        ),
    ]
