# Generated by Django 4.2.20 on 2026-09-20 21:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_alter_article_canonical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='کاربری که این مقاله را در پنل مدیریت ثبت کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, help_text='زمان تقریبی مطالعه مقاله بر حسب دقیقه (در صورت خالی بودن، خودکار بر اساس متن محاسبه می\u200cشود).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='زمان مطالعه'),
        ),
    ]
