# Generated by Django 4.2.20 on 2026-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_article_creator_alter_article_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='تصویر اصلی مقاله که در لیست مقالات و صفحه جزئیات نمایش داده می\u200cشود.', max_length=500, null=True, upload_to='blogs/articles/%Y/%m/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, help_text='تصویری که هنگام اشتراک\u200cگذاری مقاله در شبکه\u200cهای اجتماعی نمایش داده می\u200cشود.', max_length=500, null=True, upload_to='blogs/og-images/%Y/%m/', verbose_name='تصویر اشتراک\u200cگذاری'),
        ),
    ]
