# Generated by Django 4.2.20 on 2026-10-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_article_featured_image_alter_article_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='کلمه یا عبارت کلیدی اصلی که این مقاله برای آن در موتورهای جستجو بهینه\u200cسازی می\u200cشود.', max_length=150, verbose_name='کلمه کلیدی کانونی'),
        ),
    ]
