# Generated by Django 4.2.20 on 2026-08-24 20:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(help_text='کد پیگیری ۶ رقمی منحصر به فرد برای این تیکت.', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='کد پیگیری')),
                ('title', models.CharField(help_text='عنوان کوتاه و واضح برای تیکت پشتیبانی.', max_length=200, verbose_name='عنوان تیکت')),
                ('subject', models.CharField(choices=[('ORDER', 'ثبت سفارش'), ('PAYMENT', 'پرداخت'), ('SHIPPING', 'ارسال و تحویل'), ('PRODUCT', 'مشکل محصول'), ('RETURN', 'مرجوعی'), ('ACCOUNT', 'حساب کاربری'), ('WEBSITE', 'مشکل سایت'), ('OTHER', 'سایر')], help_text='موضوع اصلی تیکت پشتیبانی را انتخاب کنید.', max_length=20, verbose_name='موضوع')),
                ('status', models.CharField(choices=[('WAITING_FOR_SUPPORT', 'در انتظار پشتیبانی'), ('WAITING_FOR_USER', 'در انتظار کاربر'), ('CLOSED', 'بسته شده')], default='WAITING_FOR_SUPPORT', help_text='وضعیت فعلی تیکت و نوبت ارسال پیام.', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد تیکت.', verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین تغییر در تیکت.', verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(help_text='کاربری که این تیکت را ایجاد کرده است.', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='متن پیام.', verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ارسال پیام.', verbose_name='تاریخ ارسال')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین ویرایش پیام.', verbose_name='تاریخ بروزرسانی')),
                ('sender', models.ForeignKey(help_text='کاربری که این پیام را ارسال کرده است.', on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
                ('ticket', models.ForeignKey(help_text='تیکتی که این پیام به آن تعلق دارد.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='فایل پیوست شده به پیام.', upload_to='support/attachments/%Y/%m/', verbose_name='فایل')),
                ('original_name', models.CharField(help_text='نام اصلی فایل قبل از آپلود.', max_length=255, verbose_name='نام اصلی فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان آپلود فایل.', verbose_name='تاریخ آپلود')),
                ('message', models.ForeignKey(help_text='پیامی که این فایل به آن پیوست شده است.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'پیوست تیکت',
                'verbose_name_plural': 'پیوست\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0cd9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['sender'], name='support_tic_sender__b8ff9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tracking_code'], name='support_tic_trackin_63c62d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', '-created_at'], name='support_tic_user_id_b8c0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='support_tic_status_363e60_idx'),
        ),
    ]
