"""
This module defines the data models for the Sidoos blog application.

It contains the Article model, which represents published and draft
magazine articles for the Sidoos B2B wholesale e-commerce platform.

The Article model stores:
- Persian/Unicode content (title, summary, content, slug)
- Publication state (draft/published)
- Reading time metadata
- Tags for related articles
- SEO and social sharing metadata
- Automatic timestamps

Architectural decisions:
- Slugs are stored as CharField to support Persian/Unicode characters,
  as Django's SlugField enforces ASCII-only validation.
- Dates are stored as timezone-aware DateTime, not Persian strings,
  to keep database storage independent from presentation.
- Reading time is stored as an integer for localization flexibility.
- SEO fields are stored directly on Article for simplicity.
- Table of Contents generation is intentionally not implemented here;
  it belongs to the presentation layer.

Important:
The model must not manually encode/decode Unicode slugs. URL encoding
is handled by the web server and Django's URL routing layer.
"""

import re

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from django_ckeditor_5.fields import CKEditor5Field
from taggit.managers import TaggableManager


class Article(models.Model):
    """
    Represents a Sidoos magazine article.

    Articles can be stored as drafts or published content and contain
    Persian/Unicode metadata, HTML content generated by CKEditor 5,
    tags, publication information, and SEO metadata.

    The model intentionally does not contain presentation logic such as
    Jalali date formatting or Table of Contents generation. These
    concerns are handled in the template/presentation layer.

    Slug storage:
    The slug field uses CharField instead of SlugField to support
    Persian/Unicode characters. The slug must be URL-safe and unique,
    but is not restricted to ASCII characters.
    """

    # ============================================================
    # Core Article Fields
    # ============================================================

    title = models.CharField(
        max_length=200,
        verbose_name="عنوان مقاله",
        help_text="عنوان اصلی مقاله را وارد کنید.",
    )

    slug = models.CharField(
        max_length=255,
        unique=True,
        verbose_name="اسلاگ",
        help_text=(
            "شناسه یکتای مقاله در URL. می‌تواند شامل حروف فارسی، "
            "اعداد و خط تیره باشد."
        ),
    )

    summary = models.TextField(
        verbose_name="خلاصه مقاله",
        help_text="خلاصه کوتاهی از مقاله که در کارت‌ها و لیست مقالات نمایش داده می‌شود.",
    )

    featured_image = models.ImageField(
        upload_to="blogs/articles/%Y/%m/",
        null=True,
        blank=True,
        verbose_name="تصویر شاخص",
        help_text="تصویر اصلی مقاله که در لیست مقالات و صفحه جزئیات نمایش داده می‌شود.",
    )

    content = CKEditor5Field(
        verbose_name="متن مقاله",
        help_text="محتوای کامل مقاله با فرمت HTML که توسط CKEditor 5 تولید می‌شود.",
        config_name="default",
    )

    # ============================================================
    # Publication & Scheduling
    # ============================================================

    reading_time = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(60)],
        verbose_name="زمان مطالعه",
        help_text="زمان تقریبی مطالعه مقاله بر حسب دقیقه (فقط عدد وارد شود).",
    )

    published_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="تاریخ انتشار",
        help_text="تاریخ و زمان انتشار مقاله. برای پیش‌نویس می‌تواند خالی باشد.",
    )

    is_published = models.BooleanField(
        default=False,
        verbose_name="انتشار مقاله",
        help_text="با فعال کردن این گزینه، مقاله در سایت برای کاربران قابل مشاهده خواهد بود.",
    )

    # ============================================================
    # Tags
    # ============================================================

    tags = TaggableManager(
        verbose_name="برچسب‌ها",
        help_text="برچسب‌های مرتبط با مقاله را وارد کنید. این برچسب‌ها برای نمایش مقالات مرتبط استفاده می‌شوند.",
        blank=True,
    )

    # ============================================================
    # SEO Metadata
    # ============================================================

    meta_title = models.CharField(
        max_length=200,
        blank=True,
        verbose_name="عنوان سئو",
        help_text="عنوانی که موتورهای جستجو برای این مقاله نمایش می‌دهند. بهتر است کوتاه، دقیق و مرتبط با محتوای مقاله باشد.",
    )

    meta_description = models.TextField(
        blank=True,
        verbose_name="توضیحات سئو",
        help_text="توضیح کوتاهی درباره محتوای مقاله که می‌تواند در نتایج موتورهای جستجو نمایش داده شود.",
    )

    canonical_url = models.URLField(
        blank=True,
        verbose_name="آدرس canonical",
        help_text="در صورت نیاز، آدرس اصلی و ترجیحی این مقاله را وارد کنید.",
    )

    og_title = models.CharField(
        max_length=200,
        blank=True,
        verbose_name="عنوان اشتراک‌گذاری",
        help_text="عنوانی که هنگام اشتراک‌گذاری مقاله در شبکه‌های اجتماعی نمایش داده می‌شود.",
    )

    og_description = models.TextField(
        blank=True,
        verbose_name="توضیحات اشتراک‌گذاری",
        help_text="توضیحی که هنگام اشتراک‌گذاری مقاله در شبکه‌های اجتماعی نمایش داده می‌شود.",
    )

    og_image = models.ImageField(
        upload_to="blogs/og-images/%Y/%m/",
        null=True,
        blank=True,
        verbose_name="تصویر اشتراک‌گذاری",
        help_text="تصویری که هنگام اشتراک‌گذاری مقاله در شبکه‌های اجتماعی نمایش داده می‌شود.",
    )

    robots = models.CharField(
        max_length=50,
        default="index,follow",
        blank=True,
        verbose_name="تنظیمات robots",
        help_text="تنظیمات مربوط به نحوه مشاهده و ایندکس شدن مقاله توسط موتورهای جستجو.",
    )

    # ============================================================
    # Automatic Timestamps
    # ============================================================

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="تاریخ ایجاد",
        help_text="تاریخ و زمان ایجاد مقاله (به صورت خودکار ثبت می‌شود).",
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name="تاریخ به‌روزرسانی",
        help_text="تاریخ و زمان آخرین به‌روزرسانی مقاله (به صورت خودکار ثبت می‌شود).",
    )

    class Meta:
        """
        Model metadata configuration.

        Sets Persian verbose names and defines default ordering to show
        newest articles first based on publication date.
        """

        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
        ordering = ["-published_at", "-created_at"]
        indexes = [
            models.Index(fields=["is_published", "-published_at"]),
        ]

    def __str__(self) -> str:
        """
        Returns the article title as the human-readable representation.

        Returns:
            The article title string.
        """
        return self.title

    def clean(self) -> None:
        """
        Performs model-level validation.

        Validates that:
        - The slug contains only URL-safe characters (Persian, English,
          numbers, hyphens, underscores)
        - Published articles have a publication date

        Raises:
            ValidationError: If any validation rule is violated.
        """
        super().clean()

        # Validate slug format: only Persian/English chars, numbers,
        # hyphens, underscores, and spaces (spaces will be converted to hyphens)
        slug_pattern = re.compile(r'^[\w\u0600-\u06FF\s\-]+$')
        if not slug_pattern.match(self.slug):
            raise ValidationError({
                'slug': 'اسلاگ فقط می‌تواند شامل حروف فارسی، حروف انگلیسی، اعداد، خط تیره و فاصله باشد.'
            })

        # Replace spaces with hyphens in slug for URL safety
        self.slug = self.slug.replace(' ', '-')

        # Validate publication logic
        if self.is_published and not self.published_at:
            raise ValidationError({
                'published_at': 'برای انتشار مقاله، تاریخ انتشار الزامی است.'
            })

    def save(self, *args, **kwargs) -> None:
        """
        Saves the Article instance after running validation.

        Args:
            *args: Variable length argument list.
            **kwargs: Arbitrary keyword arguments.
        """
        self.full_clean()
        super().save(*args, **kwargs)